name: Fetch and Rename EPG

on:
  # Runs the action every day at 4 AM
  schedule:
    - cron: '0 4 * * *'

  # Allows you to manually run the action from GitHub's UI
  workflow_dispatch:

jobs:
  fetch_epg:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Fetch the EPG file from the external site
    - name: Fetch EPG file
      run: |
        curl -o epgid.xml https://www.bevy.be/generate/sZ7jyV7tWe.xml  # Replace with your EPG URL

    # Step 4: Configure Git with your credentials
    - name: Set up Git
      run: |
        git add epgid.xml
        git commit -m "Update EPG file"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.FETCH_TOKEN }}
    
