name: Fetch EPG 

on:
  # Runs the action every day at 4 AM UTC
  schedule:
    - cron: '0 4 * * *'

  # Allows you to manually run the action from GitHub's UI
  workflow_dispatch:

jobs:
  fetch_epg:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Fetch the EPG file from the external site
      - name: Fetch EPG file
        run: |
          curl -o epgid.xml https://www.bevy.be/bevyfiles/indonesiapremium3.xml  # Replace with your EPG URL

      # Step 3: Commit and push EPG file without global Git config
      - name: Commit and push EPG file
        run: |
          git add epgid.xml
          git commit -m "Update EPG file" --author="GitHub Actions Bot <github-actions[bot]@users.noreply.github.com>"
          git push
