name: Download and Unzip EPG File

on:
  schedule:
    - cron: '0 4 * * *'

  workflow_dispatch:

permissions:
  contents: write  # Grant write access to the repository contents

jobs:
  download-unzip-epg:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Download the gzipped EPG file
      run: |
        curl -L https://www.bevy.be/bevyfiles/indonesiapremium3.xml.gz -o ip3.epg.xml.gz

    - name: Unzip the file
      run: |
        gunzip -f ip3.epg.xml.gz

    - name: Commit and push the unzipped file
      run: |
        git add epg.xml
        git commit -m "Update EPG file"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.FETCH_TOKEN }}
